animations {
    enabled = true

    bezier = easeOut, 0.05, 0.9, 0.1, 1.0
    bezier = easeInOut, 0.65, 0.05, 0.36, 1.0

    animation = windows, 1, 4, easeOut
    animation = windowsOut, 1, 4, easeOut
    animation = windowsMove, 1, 4, easeOut

    animation = border, 1, 4, easeOut
    animation = fade, 1, 4, easeOut

    animation = workspaces, 1, 4, easeInOut
}
