exec-once = waybar
exec-once = swaync
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset

exec-once = flatpak run org.waywallen.waywallen
exec-once = ~/.local/bin/start-waywallen-layer-shell
