general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(89b4fa)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <i>Contraseña...</i>
    rounding = 10
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}
