# ==========================================
# Monitor principal - ThinkPad A485
# ==========================================

monitor = eDP-1, 1366x768@60, 0x0, 1

# ==========================================
# Monitores externos
# ==========================================
# Hyprland detectará automáticamente cualquier
# monitor externo conectado.
monitor = , preferred, auto, 1
