# Modificador principal
$mainMod = SUPER

# Aplicaciones
$terminal = ghostty
$fileManager = nautilus
$menu = wofi --show drun

# Programas auxiliares
$browser = firefox
$editor = code

# Catppuccin Latte palette

$rosewater = rgb(f5e0e6)
$flamingo = rgb(f2cdcd)
$pink = rgb(eebebe)
$mauve = rgb(ca9ee6)
$red = rgb(e78284)
$peach = rgb(ef9f76)
$yellow = rgb(e5c890)
$green = rgb(a6d189)
$teal = rgb(81c8be)
$sky = rgb(99d1db)
$sapphire = rgb(85c1dc)
$blue = rgb(8caaee)
$lavender = rgb(babbf1)

$text = rgb(c6d0f5)
$subtext1 = rgb(b5bfe2)
$subtext0 = rgb(a5adce)

$base = rgb(303446)
$mantle = rgb(292c3c)
$crust = rgb(232634)

$surface0 = rgb(8a8c99)
$surface1 = rgb(6e7086)
$surface2 = rgb(565970)
